### ISSUE TITLE
Unable to build examples

### ISSUE THREAD

**Issue by fazpu** [yagajs/leaflet-ng2#244]
Hi,

I have been unable to build and run examples.

After yarn install and yarn  run build-examples, I get:

```
+ npm run transpile
npm ERR! Error: Invalid name: "@yaga/leaflet-ng2"
npm ERR!     at ensureValidName (/home/github/angular-maps/leaflet-ng2/node_modules/npm/node_modules/read-package-json/node_modules/normalize-package-data/lib/fixer.js:281:15)
npm ERR!     at Object.fixNameField (/home/github/angular-maps/leaflet-ng2/node_modules/npm/node_modules/read-package-json/node_modules/normalize-package-data/lib/fixer.js:196:5)
npm ERR!     at /home/github/angular-maps/leaflet-ng2/node_modules/npm/node_modules/read-package-json/node_modules/normalize-package-data/lib/normalize.js:29:38
npm ERR!     at Array.forEach (native)
npm ERR!     at normalize (/home/github/angular-maps/leaflet-ng2/node_modules/npm/node_modules/read-package-json/node_modules/normalize-package-data/lib/normalize.js:28:15)
npm ERR!     at final (/home/github/angular-maps/leaflet-ng2/node_modules/npm/node_modules/read-package-json/read-json.js:342:33)
npm ERR!     at then (/home/github/angular-maps/leaflet-ng2/node_modules/npm/node_modules/read-package-json/read-json.js:126:33)
npm ERR!     at /home/github/angular-maps/leaflet-ng2/node_modules/npm/node_modules/read-package-json/read-json.js:331:40
npm ERR!     at tryToString (fs.js:449:3)
npm ERR!     at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:436:12)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 4.11.6-041106-generic
npm ERR! command "/usr/bin/nodejs" "/home/github/angular-maps/leaflet-ng2/node_modules/.bin/npm" "run" "transpile"
npm ERR! cwd /home/github/angular-maps/leaflet-ng2
npm ERR! node -v v7.10.0
npm ERR! npm -v 1.3.1
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/github/angular-maps/leaflet-ng2/npm-debug.log
npm ERR! not ok code 0
+ browserify tile-layer-directive/index.js -o tile-layer-directive/bundle.js
events.js:163
      throw er; // Unhandled 'error' event
      ^

Error: ENOENT: no such file or directory, open 'tile-layer-directive/bundle.js.tmp-browserify-44473743751580552264'
error Command failed with exit code 1.

```

**Comment by marcjansen** [comment]
ouch, sorry for the close, it was unintentional

**Comment by atd-schubert** [comment]
As long as I could not get a look at this problem, you can try out the examples on our [project server](https://leaflet-ng2.yagajs.org) in the [examples](https://leaflet-ng2.yagajs.org/latest/examples/) section.

**Comment by atd-schubert** [comment]
I think you have not really a problem with the command `yarn build-examples`. Your problem starts during `yarn install`. This should throw an error like this:

`error Couldn't find a package.json file in 
 "[...]/node_modules/npm/node_modules/normalize-package-data"`

In any case I don't think it is a bug on this library, it is a bug in `yarn` or maybe `normalize-package-data`.

Your problem should be solved by reinstalling the modules. Like this:
```bash
rm -Rf node-modues && npm install
```

Now you can even use `yarn` or of course `npm` for creating the examples:

```bash
yarn run build-examples || npm run build-examples
```

**Comment by atd-schubert** [comment]
Maybe I was not able to reproduce this error because of my package-lock file that is not present in Git but on my computer.

I will take a look again...

**Comment by atd-schubert** [comment]
There are a bunch of problems with some dependencies on a clean installation now. Let's reopen and go into detail...

**Comment by atd-schubert** [comment]
Can not be used with the newest version:
* typescript: angular-core is incompatible with the newest typescript 4.x. We should remove the `^` in package.json and add as long as it is unsupported a fixed version.
* leaflet: Has a bug that is already [fixed in version 1.1.0](https://github.com/Leaflet/Leaflet/pull/5596). The current version `1.1.0` of Leaflet is incompatible to to this module. The mentioned PR is already merged, so in the next version we can add the `^` again...

Some dependencies can be updated by the way:

* types/chai
* chai
* jsdom
* jsdom-global
* rxjs
* typedoc


*tslint also, but it takes also a lot of work, so I will create another issue for that...*

**Comment by atd-schubert** [comment]
The helper cli `node-dependencies` causing trouble on `yarn`. It installs `npm` as dependency and should be removed.

Additional, we don't have to use it anymore. The `npm outdated` command should provide everything we want to have and if someone want to use node-outdated, he can install it as global module.

We can also remove some other development dependencies and their script tasks that we do not need anymore, like `ts-npm-lint`.

**Comment by atd-schubert** [comment]
see #248

**Comment by fazpu** [comment]
Thank you very much for the quick response and the PR!

Unfortunatelly, I am still getting errors after `rm -Rf node-modues && npm install` and `npm run build-examples` (using npm, even when swithed to the issue-244 branch).

Error message:

```
> @yaga/leaflet-ng2@1.0.0 build-examples /home/github/angular-maps/leaflet-ng2
> set -x && npm run transpile && cd examples && tsc; browserify tile-layer-directive/index.js -o tile-layer-directive/bundle.js && browserify map-component/index.js -o map-component/bundle.js && browserify zoom-control-directive/index.js -o zoom-control-directive/bundle.js && browserify scale-control-directive/index.js -o scale-control-directive/bundle.js && browserify attribution-control-directive/index.js -o attribution-control-directive/bundle.js && browserify circle-marker-directive/index.js -o circle-marker-directive/bundle.js && browserify image-overlay-directive/index.js -o image-overlay-directive/bundle.js && browserify icon-directive/index.js -o icon-directive/bundle.js && browserify passau/index.js -o passau/bundle.js

+ npm run transpile
npm ERR! Error: Invalid name: "@yaga/leaflet-ng2"
npm ERR!     at ensureValidName (/home/github/angular-maps/leaflet-ng2/node_modules/npm/node_modules/read-package-json/node_modules/normalize-package-data/lib/fixer.js:300:15)
npm ERR!     at Object.fixNameField (/home/github/angular-maps/leaflet-ng2/node_modules/npm/node_modules/read-package-json/node_modules/normalize-package-data/lib/fixer.js:204:5)
npm ERR!     at /home/github/angular-maps/leaflet-ng2/node_modules/npm/node_modules/read-package-json/node_modules/normalize-package-data/lib/normalize.js:30:38
npm ERR!     at Array.forEach (native)
npm ERR!     at normalize (/home/github/angular-maps/leaflet-ng2/node_modules/npm/node_modules/read-package-json/node_modules/normalize-package-data/lib/normalize.js:29:15)
npm ERR!     at final (/home/github/angular-maps/leaflet-ng2/node_modules/npm/node_modules/read-package-json/read-json.js:342:33)
npm ERR!     at then (/home/github/angular-maps/leaflet-ng2/node_modules/npm/node_modules/read-package-json/read-json.js:126:33)
npm ERR!     at /home/github/angular-maps/leaflet-ng2/node_modules/npm/node_modules/read-package-json/read-json.js:331:40
npm ERR!     at tryToString (fs.js:449:3)
npm ERR!     at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:436:12)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 4.11.6-041106-generic
npm ERR! command "/usr/bin/nodejs" "/home/github/angular-maps/leaflet-ng2/node_modules/.bin/npm" "run" "transpile"
npm ERR! cwd /home/github/angular-maps/leaflet-ng2
npm ERR! node -v v7.10.0
npm ERR! npm -v 1.3.1
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/github/angular-maps/leaflet-ng2/npm-debug.log
npm ERR! not ok code 0
+ browserify tile-layer-directive/index.js -o tile-layer-directive/bundle.js
events.js:163
      throw er; // Unhandled 'error' event
      ^

Error: ENOENT: no such file or directory, open 'tile-layer-directive/bundle.js.tmp-browserify-91274443809783001313'

npm ERR! Linux 4.11.6-041106-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "build-examples"
npm ERR! node v7.10.0
npm ERR! npm  v4.2.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @yaga/leaflet-ng2@1.0.0 build-examples: `set -x && npm run transpile && cd examples && tsc; browserify tile-layer-directive/index.js -o tile-layer-directive/bundle.js && browserify map-component/index.js -o map-component/bundle.js && browserify zoom-control-directive/index.js -o zoom-control-directive/bundle.js && browserify scale-control-directive/index.js -o scale-control-directive/bundle.js && browserify attribution-control-directive/index.js -o attribution-control-directive/bundle.js && browserify circle-marker-directive/index.js -o circle-marker-directive/bundle.js && browserify image-overlay-directive/index.js -o image-overlay-directive/bundle.js && browserify icon-directive/index.js -o icon-directive/bundle.js && browserify passau/index.js -o passau/bundle.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @yaga/leaflet-ng2@1.0.0 build-examples script 'set -x && npm run transpile && cd examples && tsc; browserify tile-layer-directive/index.js -o tile-layer-directive/bundle.js && browserify map-component/index.js -o map-component/bundle.js && browserify zoom-control-directive/index.js -o zoom-control-directive/bundle.js && browserify scale-control-directive/index.js -o scale-control-directive/bundle.js && browserify attribution-control-directive/index.js -o attribution-control-directive/bundle.js && browserify circle-marker-directive/index.js -o circle-marker-directive/bundle.js && browserify image-overlay-directive/index.js -o image-overlay-directive/bundle.js && browserify icon-directive/index.js -o icon-directive/bundle.js && browserify passau/index.js -o passau/bundle.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the @yaga/leaflet-ng2 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     set -x && npm run transpile && cd examples && tsc; browserify tile-layer-directive/index.js -o tile-layer-directive/bundle.js && browserify map-component/index.js -o map-component/bundle.js && browserify zoom-control-directive/index.js -o zoom-control-directive/bundle.js && browserify scale-control-directive/index.js -o scale-control-directive/bundle.js && browserify attribution-control-directive/index.js -o attribution-control-directive/bundle.js && browserify circle-marker-directive/index.js -o circle-marker-directive/bundle.js && browserify image-overlay-directive/index.js -o image-overlay-directive/bundle.js && browserify icon-directive/index.js -o icon-directive/bundle.js && browserify passau/index.js -o passau/bundle.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs @yaga/leaflet-ng2
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls @yaga/leaflet-ng2
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/jiripuc/.npm/_logs/2017-07-05T06_12_47_421Z-debug.log

```

**Comment by atd-schubert** [comment]
Do you have also removed your lock-file(s)? Depending on your package-installer it should be `yarn.lock`, or `package-lock.json`. Try to remove the files and try again, or maybe clone the complete repository again.


```bash
rm -Rf node-modules
rm yarn.lock package-lock.json

# using npm:
npm install

# or if you prefer yarn:
yarn install
```

Your error should occur because of `npm` as submodule. If the above described commands don't work, give me a short comment here. 

*But I think it is because of your lock file and this is why it still installs npm as dependency.*

**Comment by fazpu** [comment]
Thank you, both yarn and npm example builds are now working in the https://github.com/yagajs/leaflet-ng2/pull/248 branch.
